"""Add relationship between 'chats' and 'groups' tables to establish correspondence.
Update 'chats' table to include 'group_id' foreign key linking to 'groups' table.
Ensure that personal chats are associated with a group containing exactly two participants.


Revision ID: 6ff07c80cc3a
Revises: 12abab91b05e
Create Date: 2025-04-04 13:15:35.573835

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff07c80cc3a'
down_revision: Union[str, None] = '12abab91b05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('group_id', sa.UUID(), nullable=False))
    op.create_foreign_key(
        op.f('fk_chats_group_id_groups'),
        'chats',
        'groups',
        ['group_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_chats_group_id_groups'), 'chats', type_='foreignkey',
    )
    op.drop_column('chats', 'group_id')
    # ### end Alembic commands ###
